### ISSUE TITLE
softDeletes is missing

### ISSUE THREAD

**Issue by Kerensky25** [XCMer/larry-four-generator#1]
Thanks for this component, I really like it :)

Just a minor thing, the "softDeletes" field type is currently missing.

Regards.

**Comment by XCMer** [comment]
Glad you liked it. I've added handling for softDeletes in the commit 49ac017. Once everything looks fine with the current beta, I'll release the first stable release which would include softDeletes.

**Comment by XCMer** [comment]
Larry Four 1.0.0 Stable has been released with this feature included.
