### ISSUE TITLE
Bug Problem: no line number specified when an error occurs. If you have over 1000 line files, this is a huge issue.

### ISSUE THREAD

**Issue by Xees** [XCMer/larry-four-generator#13]
I have a massive database file that i want to generate from. 

The problem is, there might be some mistakes and larry4 does not give me a specific line where the error occured.

**Comment by XCMer** [comment]
LarryFour does give you the line number of the error in the input file. Can you elaborate?

**Comment by Xees** [comment]
My error was a misspilled enum. 

I wrote it like this:

```
access enum "admin","jack","
```

by mistake, i forgot to remove the last qoute, and my file was huge.
The only error larry4 gave me was Undefined Index: type. No line number at all.

**Comment by XCMer** [comment]
That error was generated by PHP (and not Larry). It was Larry's fault that it didn't handle it. I've fixed it in 98ebb89 so that you'll get an error with line numbers in such cases.
