### ISSUE TITLE
Compatibility with Laravel 4.1

### ISSUE THREAD

**Issue by dannysuryadi** [XCMer/larry-four-generator#17]
I got this problem when trying to update my Laravel to the latest 4.1:

Your requirements could not be resolved to an installable set of packages.
Problem 1
    - raahul/larryfour v1.0.1 requires illuminate/support 4.0.x -> satisfiable by laravel/framework[4.0.x-dev, v4.0.0, ... ]

Full error report: http://pastebin.com/VHcbV9Uq

The short fix I did was to remove Larry from the project but it would be nice if it can be used in newer versions of Laravel.

**Comment by XCMer** [comment]
I'll update the composer.json for the newer versions of Laravel.

**Comment by asm0dey** [comment]
I'm second this. Please, update composer.json!

**Comment by XCMer** [comment]
A minor release 1.0.2 fixes this.

**Comment by asm0dey** [comment]
Thank you!
