### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Kerensky25** [XCMer/larry-four-generator#2]
A quick suggestion:
Add a prompt to the user when the table or model already exists, to overwrite or update it.

Like:
"User model already exists, do you want to: overwrite(O), update(U), overwrite all(A), update all(Z)"
(The same goes for existing tables/migrations)

I guess for updates it gets tricky since before updating, it would have to check not only the model/table existence but check the fields too, to not add repeated fields.

**Comment by XCMer** [comment]
I did think of this at one point. Calculating schema updates to a pre-existing database can complicate things.

For that reason, Larry is best used when kick-starting a project. After that, it is easier to create table altering migrations the conventional way.

For the time being, I will keep Larry the way it is. I'll see if I can come up with a better option. I'd love to hear what ideas others might have regarding this matter.

**Comment by XCMer** [comment]
For now, I'm not planning on adding support for incremental updates to models/migrations. So, I'm closing this issue for the moment.
